security:
    providers:
        usuario:
            entity:
                class: App\Entity\User
                property: username # or whatever property you're using as the username
    password_hashers:
        App\Entity\User:
            algorithm: argon2i
    firewalls:
        dev:
            pattern: ^/(_(confirmarCuenta|profiler|wdt)|css|images|js)/
            security: false
        main:
           form_login:
                login_path: ctrl_login
                check_path: ctrl_login
                default_target_path: app_after_login
           logout:
                path: ctrl_logout