<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerILMMx3M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerILMMx3M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerILMMx3M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerILMMx3M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerILMMx3M\App_KernelDevDebugContainer([
    'container.build_hash' => 'ILMMx3M',
    'container.build_id' => 'ed1f9621',
    'container.build_time' => 1680125478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerILMMx3M');
