<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSui59fE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSui59fE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSui59fE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSui59fE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSui59fE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sui59fE',
    'container.build_id' => '34d553c0',
    'container.build_time' => 1680486635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSui59fE');
