<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA82DeFV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA82DeFV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA82DeFV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA82DeFV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA82DeFV\App_KernelDevDebugContainer([
    'container.build_hash' => 'A82DeFV',
    'container.build_id' => '1acb6471',
    'container.build_time' => 1680647146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA82DeFV');
