<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_vue-loader_dist_exportHelper_js-node_modules_vue_dist_vue_esm-bundler_js.js',
                '/build/vendors-node_modules_axios_lib_axios_js.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/assets_styles_app_css.css',
                '/build/app.css',
            ],
        ],
        'appTwo' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_vue-loader_dist_exportHelper_js-node_modules_vue_dist_vue_esm-bundler_js.js',
                '/build/appTwo.js',
            ],
            'css' => [
                '/build/assets_styles_app_css.css',
            ],
        ],
    ],
],

]];
